// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: unittest_with_extension_1_proto3.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from unittest_with_extension_1_proto3.proto</summary>
public static partial class UnittestWithExtension1Proto3Reflection {

  #region Descriptor
  /// <summary>File descriptor for unittest_with_extension_1_proto3.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static UnittestWithExtension1Proto3Reflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CiZ1bml0dGVzdF93aXRoX2V4dGVuc2lvbl8xX3Byb3RvMy5wcm90bxomdW5p",
          "dHRlc3RfaW1wb3J0X2V4dGVuc2lvbl9wcm90bzMucHJvdG8aJnVuaXR0ZXN0",
          "X3dpdGhfZXh0ZW5zaW9uXzJfcHJvdG8zLnByb3RvGiZ1bml0dGVzdF93aXRo",
          "X2V4dGVuc2lvbl8zX3Byb3RvMy5wcm90byKnAQoZVGVzdE1lc3NhZ2VXaXRo",
          "RXh0ZW5zaW9uMRIKCgJpZBgBIAEoCRIvCgtzdWJtZXNzYWdlMhgCIAEoCzIa",
          "LlRlc3RNZXNzYWdlV2l0aEV4dGVuc2lvbjISLwoLc3VibWVzc2FnZTMYAyAB",
          "KAsyGi5UZXN0TWVzc2FnZVdpdGhFeHRlbnNpb24zOhzKPhlUZXN0TWVzc2Fn",
          "ZVdpdGhFeHRlbnNpb24xYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::UnittestImportExtensionProto3Reflection.Descriptor, global::UnittestWithExtension2Proto3Reflection.Descriptor, global::UnittestWithExtension3Proto3Reflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::TestMessageWithExtension1), global::TestMessageWithExtension1.Parser, new[]{ "Id", "Submessage2", "Submessage3" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class TestMessageWithExtension1 : pb::IMessage<TestMessageWithExtension1> {
  private static readonly pb::MessageParser<TestMessageWithExtension1> _parser = new pb::MessageParser<TestMessageWithExtension1>(() => new TestMessageWithExtension1());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<TestMessageWithExtension1> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::UnittestWithExtension1Proto3Reflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public TestMessageWithExtension1() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public TestMessageWithExtension1(TestMessageWithExtension1 other) : this() {
    id_ = other.id_;
    submessage2_ = other.submessage2_ != null ? other.submessage2_.Clone() : null;
    submessage3_ = other.submessage3_ != null ? other.submessage3_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public TestMessageWithExtension1 Clone() {
    return new TestMessageWithExtension1(this);
  }

  /// <summary>Field number for the "id" field.</summary>
  public const int IdFieldNumber = 1;
  private string id_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Id {
    get { return id_; }
    set {
      id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "submessage2" field.</summary>
  public const int Submessage2FieldNumber = 2;
  private global::TestMessageWithExtension2 submessage2_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::TestMessageWithExtension2 Submessage2 {
    get { return submessage2_; }
    set {
      submessage2_ = value;
    }
  }

  /// <summary>Field number for the "submessage3" field.</summary>
  public const int Submessage3FieldNumber = 3;
  private global::TestMessageWithExtension3 submessage3_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::TestMessageWithExtension3 Submessage3 {
    get { return submessage3_; }
    set {
      submessage3_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as TestMessageWithExtension1);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(TestMessageWithExtension1 other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Id != other.Id) return false;
    if (!object.Equals(Submessage2, other.Submessage2)) return false;
    if (!object.Equals(Submessage3, other.Submessage3)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Id.Length != 0) hash ^= Id.GetHashCode();
    if (submessage2_ != null) hash ^= Submessage2.GetHashCode();
    if (submessage3_ != null) hash ^= Submessage3.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (Id.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Id);
    }
    if (submessage2_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(Submessage2);
    }
    if (submessage3_ != null) {
      output.WriteRawTag(26);
      output.WriteMessage(Submessage3);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Id.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
    }
    if (submessage2_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Submessage2);
    }
    if (submessage3_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Submessage3);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(TestMessageWithExtension1 other) {
    if (other == null) {
      return;
    }
    if (other.Id.Length != 0) {
      Id = other.Id;
    }
    if (other.submessage2_ != null) {
      if (submessage2_ == null) {
        Submessage2 = new global::TestMessageWithExtension2();
      }
      Submessage2.MergeFrom(other.Submessage2);
    }
    if (other.submessage3_ != null) {
      if (submessage3_ == null) {
        Submessage3 = new global::TestMessageWithExtension3();
      }
      Submessage3.MergeFrom(other.Submessage3);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Id = input.ReadString();
          break;
        }
        case 18: {
          if (submessage2_ == null) {
            Submessage2 = new global::TestMessageWithExtension2();
          }
          input.ReadMessage(Submessage2);
          break;
        }
        case 26: {
          if (submessage3_ == null) {
            Submessage3 = new global::TestMessageWithExtension3();
          }
          input.ReadMessage(Submessage3);
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
