// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: unittest_import_extension_proto3.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from unittest_import_extension_proto3.proto</summary>
public static partial class UnittestImportExtensionProto3Reflection {

  #region Descriptor
  /// <summary>File descriptor for unittest_import_extension_proto3.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static UnittestImportExtensionProto3Reflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CiZ1bml0dGVzdF9pbXBvcnRfZXh0ZW5zaW9uX3Byb3RvMy5wcm90bxogZ29v",
          "Z2xlL3Byb3RvYnVmL2Rlc2NyaXB0b3IucHJvdG86PAoSdW5pdHRlc3RfZXh0",
          "ZW5zaW9uEh8uZ29vZ2xlLnByb3RvYnVmLk1lc3NhZ2VPcHRpb25zGOkHIAEo",
          "CWIGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::Google.Protobuf.Reflection.DescriptorReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, new pb::Extension[] { UnittestImportExtensionProto3Extensions.UnittestExtension }, null));
  }
  #endregion

}
/// <summary>Holder for extension identifiers generated from the top level of unittest_import_extension_proto3.proto</summary>
public static partial class UnittestImportExtensionProto3Extensions {
  public static readonly pb::Extension<global::Google.Protobuf.Reflection.MessageOptions, string> UnittestExtension =
    new pb::Extension<global::Google.Protobuf.Reflection.MessageOptions, string>(1001, pb::FieldCodec.ForString(8010, ""));
}


#endregion Designer generated code
